export const queriesloteterminado = {

    getLoteTerminado:
    'select Cantidad_inicial_pollos,Costo_pollo_unidad,Id_lote_produccion,reg_mort.Cantidad_pollos_muertos Total_pollos_muertos,reg_sacri.Fecha_sacrificio  Fecha_sacrificio_final,reg_sacri.Cantidad_pollos Total_pollos_sacrificados,reg_alim.Cantidad_alimento Cantidad_total_alimento,reg_alim.Precio_compra     Valor_total_alimento,gast_prod.gasto_total Gasto_total_produccion from Lote_produccion left join (select Id_ref_lote_produccion Id_ref_lote_produccion, CASE WHEN Sum(Cantidad_pollos_muertos)IS NULL THEN 0 ELSE Sum(Cantidad_pollos_muertos) END Cantidad_pollos_muertos from Reg_produccion_mortalidad GROUP BY Id_ref_lote_produccion) reg_mort on reg_mort.Id_ref_lote_produccion = Id_lote_produccion left join (select Id_ref_lote_produccion Id_ref_lote_produccion, MAX(Fecha_sacrificio) Fecha_sacrificio, CASE WHEN SUM(Cantidad_pollos) IS NULL THEN 0 ELSE SUM(Cantidad_pollos) END Cantidad_pollos FROM Reg_sacrificio_pollo GROUP BY Id_ref_lote_produccion)reg_sacri ON reg_sacri.Id_ref_lote_produccion = Id_lote_produccion left join (select Id_ref_lote_produccion Id_ref_lote_produccion, CASE WHEN SUM(Cantidad_alimento) IS NULL THEN 0 ELSE SUM(Cantidad_alimento) END Cantidad_alimento, CASE WHEN SUM(Precio_compra) IS NULL THEN 0 ELSE SUM(Precio_compra) END  Precio_compra FROM  Reg_produccion_alimento group by Id_ref_lote_produccion )reg_alim on reg_alim.Id_ref_lote_produccion = Id_lote_produccion left join (SELECT  Id_ref_lote_produccion Id_ref_lote_produccion, SUM(Cantidad * Precio) gasto_total FROM Gastos_produccion GROUP BY Id_ref_lote_produccion ) gast_prod ON gast_prod.Id_ref_lote_produccion = Id_lote_produccion where Id_ref_lote = @Id_ref_lote  GROUP BY Cantidad_inicial_pollos,Costo_pollo_unidad,Id_lote_produccion,reg_mort.Cantidad_pollos_muertos,reg_sacri.Fecha_sacrificio,reg_sacri.Cantidad_pollos ,reg_alim.Cantidad_alimento,reg_alim.Precio_compra  ,gast_prod.gasto_total',

    getLoteVenta:
    'select  Id_lote_venta_total, vr.Cantidad_pollos Total_pollos_vendidos ,vr.peso_vendido Peso_total_vendido ,vr.Valor_unidad_peso  Valor_promedio_peso ,vr.Total_venta  Total_venta_lote ,vr.Total_venta  Ganancia_bruta ,vr.cantidad_promedio Promedio_total_peso ,vr.cantidad_ventas Cantidad_ventas ,gvp.Precio Gastos_total_ventas from  Lote_venta left join (SELECT SUM(Lot_ven_reg.Cantidad_pollos) Cantidad_pollos,SUM(Lot_ven_reg.Cantidad) peso_vendido ,AVG(Lot_ven_reg.Valor_unidad_peso) Valor_unidad_peso,SUM(Lot_ven_reg.Total_venta) Total_venta, AVG(Lot_ven_reg.Cantidad) cantidad_promedio,COUNT(Lot_ven_reg.Id_lote_ventas_registro) cantidad_ventas, Lot_ven_reg.Id_ref_lote_venta  FROM Lote_ventas_registro Lot_ven_reg  GROUP BY Lot_ven_reg.Id_ref_lote_venta ) vr on vr.Id_ref_lote_venta = Id_lote_venta_total    LEFT JOIN (SELECT SUM(gas_ven.Precio * gas_ven.Cantidad) Precio,gas_ven.Id_ref_lote_venta  from Gastos_ventas gas_ven GROUP BY gas_ven.Id_ref_lote_venta  ) gvp ON  gvp.Id_ref_lote_venta = Id_lote_venta_total where Id_ref_lote =@Id_ref_lote',

    getLote_Venta_Produccion:
    'select  lp.Consumo_pollo ,lvr.Peso_total_vendido ,lvr.Ganancia_bruta ,gv.Gastos_ventas ,lp.Costo_total_lote ,lp.Id_lote_produccion ,lvr.Id_lote_venta_total from Lote_produccion lp LEFT join Lote_venta lvr on lvr.Id_ref_lote = lp.Id_ref_lote LEFT JOIN (select SUM(Precio * Cantidad) Gastos_ventas, Id_ref_lote_venta from Gastos_ventas group by Id_ref_lote_venta) gv on  gv.Id_ref_lote_venta = lvr.Id_lote_venta_total where lp.Id_ref_lote= @Id_ref_lote',

}